name: "context examples"

on: ['push']

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: "1st step"
        run: echo "Action $MY_ACTION"
        env:
          MY_ACTION: ${{ github.action }}
      - name: "2st step"
        run: echo "Hello $MY_ACTOR"
        env:
          MY_ACTOR: ${{ github.actor }}